### ISSUE TITLE
The message string requires \r\n

### ISSUE THREAD

**Issue by Yoshi2889** [phergie/phergie-irc-parser#10]
While using your parser in our project we noticed that the message string requires \r\n to be at the end, for example:

Won't work: string: :user PRIVMSG #channel :message
Will work: string: :user PRIVMSG #channel :message\r\n

In our opinion, this should either be explicitly noted or be made optional.

**Comment by elazar** [comment]
The README file for this library notes that it is modeled after RFC 1459. The last paragraph of [Section 2.3](https://tools.ietf.org/html/rfc1459#section-2.3) of that RFC already explicitly notes what you've described:

> IRC messages are always lines of characters terminated with a CR-LF (Carriage Return - Line Feed) pair.

This is reflected in several areas of this repository:

* [The usage example](https://github.com/phergie/phergie-irc-parser#usage) in the README file
* [Test cases](https://github.com/phergie/phergie-irc-parser/blob/53483817974f7a38b1aaafd10fab18114ada1443/tests/ParserTest.php#L93) for incomplete and complete messages and how they're parsed in the test suite
* The [`$message` pattern](https://github.com/phergie/phergie-irc-parser/blob/53483817974f7a38b1aaafd10fab18114ada1443/src/Parser.php#L213) in the code for the parser itself, which is fairly readable and consistent with respect to the BNF notation included in the RFC

Given all this, I'm not sure it bears further repetition or other explicit mention.

However, if you'd like to submit a pull request that augments the current usage example with one that explicitly shows that incomplete messages are not parsed, I'd be happy to review it.

**Comment by Yoshi2889** [comment]
Sorry for not replying earlier. We have adapted our code to better comply with the spec, so this issue is redundant now :)
