### ISSUE TITLE
Numeric parsing

### ISSUE THREAD

**Issue by Renegade334** [phergie/phergie-irc-parser#14]
The syntax for numeric commands is such that the bot's nickname always appears after the initial numeric:

`XXX BotNick Param1 Param2 :ParamTrail`

However, the parser isn't configured to extract the bot's nickname within the numeric, and parses it as the first parameter.

(Changing this behaviour will impact any downstream modules that process numeric parameters.)

**Comment by elazar** [comment]
What would be the benefit of making this change? Can you provide an example use case? As you've pointed out, a drawback would be potential backward compatibility breakage. I'm hesitant to make a change that doesn't result in some positive benefit for the end user.

**Comment by Renegade334** [comment]
It's just logically inconsistent, since the bot's nickname is not a true parameter of the specific numeric event itself, it's just part of the structure for numeric replies. It is never going to be of any use for event handlers that use the parameters.

There would be no harm in extracting it to a separate `$parsed` element (`'target'` maybe?), but I don't think it's useful always having it as the first element in `$parsed['params']`, as it's only going to need to be discarded whenever the params are actually processed by an event handler.

On the breakage front, only one core Phergie plugin actually processes individual params for a numeric event, which is UserMode, as well as one non-core plugin on the wiki, OpsWorksDeployment (@blopboard), which would just need the relevant parameter index decreasing by 1.

**Comment by elazar** [comment]
`'target'` would probably make sense. Is this something you'd be willing to submit a PR for?

**Comment by Renegade334** [comment]
Sure, will do.

**Comment by elazar** [comment]
PR looks good. Could you provide specifics on what areas of the OpsWorksDeployment and UserModes plugins would require updates, maybe submit PRs for them as well? In doing a quick skim of both, it seems like they're all using named parameters.

**Comment by Renegade334** [comment]
UserMode's parsing of RPL_NAMREPLY in `loadUserModes()` used `array_shift()` on the params array, and then run a `foreach` on the remainder. This actually already assumed that the first parameter was `#channel` and not `TargetUser`, so it was broken before anyway!

However, it was broken for other reasons as well, ie. assuming that the `(=|*|@)` channel privacy sigil was prepended to `#channel` rather than its own individual param. I have addressed this as part of a set of fixes and improvements for UserMode [[branch](https://github.com/Renegade334/phergie-irc-plugin-react-usermode/compare/devel)] which is dependent on the PROTOCTL changes as well as on this change to the parser. Will need some tags for dependency management, so once those are in place, I will update `composer.json` and request the merge.

OpsWorksDeployment needs a very simple change to its `topicPrompt()` method, which listens for ERR_CHANOPRIVSNEEDED:
``` diff
diff --git a/src/Plugin.php b/src/Plugin.php
index 0584770..50b6feb 100644
--- a/src/Plugin.php
+++ b/src/Plugin.php
@@ -162,7 +162,7 @@ class Plugin extends AbstractPlugin implements LoopAwareInterface
     public function topicPrompt(EventInterface $event, Queue $queue)
     {
         $params = $event->getParams();
-        $channel = $params[1];
+        $channel = $params[0];
         $message = 'Can\'t change topic, please run /MODE ' . $channel . ' -t';
         $queue->ircPrivmsg($channel, $message);
     }
```
