### ISSUE TITLE
Channel MODE parsing and multiple mode changes

### ISSUE THREAD

**Issue by Renegade334** [phergie/phergie-irc-parser#17]
If a MODE message is received with a channel target, the parser will then [attempt to sub-parse the message](https://github.com/phergie/phergie-irc-parser/blob/ad796d9cb7bea572360a4b4e1cc546c1a90599ab/src/Parser.php#L346-358). This algorithm basically states "if the mode string contains a 'b', the trailing string is a banmask; else if it contains a 'k', it's a channel key; else..."

However, this assumes that only one mode change is being made. If a message such as `MODE #channel +b-o *!*@some.host ChanOpUser` is parsed, the string `*!*@some.host ChanOpUser` is assigned to `$params['banmask']`, and `$params['user']` (where one would ordinarily find the `ChanOpUser` param) does not exist.

MODE messages may also have a different number of trailing parameters than modes (eg. `MODE #channel +vvm TrustedUser1 TrustedUser2`), so there is no uniform way to reliably associate modes with the respective parameters. (Clients may achieve this by parsing the `MODES` element of the `005 RPL_NAMREPLY` numeric, which identifies which modes take parameters and which don't, but a contextless parser cannot.)

As such, I wonder if it's truly valid for an RFC-compliant parser to be processing the MODE string in this way. At the least, some kind of common named parameter should be made available so that the trailing parameters can be accessed in a consistent way.

**Comment by elazar** [comment]
It looks like support for multiple mode specifications in a single message is a difference in RFC 1459 (specifically section [4.2.3](https://tools.ietf.org/html/rfc1459#section-4.2.3)), on which this parser was originally based, and RFC 2812 (specifically sections [3.1.5](https://tools.ietf.org/html/rfc2812#section-3.1.5) and [3.2.3](https://tools.ietf.org/html/rfc2812#section-3.2.3)), hence its absence in the current implementation. This should be addressed.

**Comment by elazar** [comment]
To avoid breaking BC in existing plugins, we could check that only a single known mode is being set and use the existing logic in that case, else simply include the modes and parameters in enumerated arrays.

**Comment by Renegade334** [comment]
Sounds like a good idea, provided that `$params['params']` is still made available in those cases. Maybe a deprecation notice in the source comments?

**Comment by elazar** [comment]
Not sure we even need that so long as the modes are standard across 2812 or both RFCs.

Another related idea: if we added accessor methods to `Client` for the parser, which would then be injected into any `ReadStream` instances that `Client` created internally, any plugin that implemented `ClientAwareInterface` would have access to the parser. At that point, we could add methods to the parser to inject context information for server-supported modes and create a plugin that handled delivering that information to the parser. Not certain it's feasible or something that should be considered yet, but it's an idea.

**Comment by Renegade334** [comment]
What do you think of 9d064180518b1a320afc913b08dd3309e0f13d5a?

**Comment by elazar** [comment]
@Renegade334 Looks good. Can you submit it as a PR?

**Comment by Renegade334** [comment]
Sure!

**Comment by Renegade334** [comment]
@elazar: re. the context-aware parser idea above: since each connection might have different channel mode types if they're connected to different servers, I'm not sure this is feasible. I think a utility plugin may be a better option - have put together an example implementation at [phergie-irc-plugin-react-chanmodeparser](https://github.com/Renegade334/phergie-irc-plugin-react-chanmodeparser/blob/devel/src/Plugin.php).
