### ISSUE TITLE
Resilience against invalid lines

### ISSUE THREAD

**Issue by Renegade334** [phergie/phergie-irc-parser#23]
Currently, `parse()` returns `NULL` on both an incomplete line (no CRLF) and an invalid line (as per regex parsing).

This means that if a line is received where any of the line elements fail their respective regexes, `parse()` returns `NULL`. This causes `parseAll()` and `consumeAll()` to break, as they never receive any further output from `parse()`, and the client stops receiving any further input and freezes.

aa2ea5f0ca is one way of solving this issue. It separates incomplete line detection, which is performed with simple string matching at the top of the function, from invalid line detection through `preg_match()`. Incomplete lines will still return `NULL` as before, whereas invalid lines will return an array containing the invalid line and the tail.

Such a change would require changes to the client to detect the presence of the `'invalid'` key in the returned message array, and log it without emitting it as a message event.

Submitting here as a request for comment, more than anything. I'm on holiday currently, so just stopping by...!

**Comment by elazar** [comment]
The client freezing is a condition we've suffered for before in debugging parser issues, so I'm definitely all for something that makes that easier. Can you submit a PR that contains aa2ea5f and submit an issue or PR against the client repo that would have it log when invalid messages are detected?

**Comment by elazar** [comment]
Merged #27.
